import type { CityData, CityStatute } from './cityData';

export type DocumentType = 'eviction-answer' | 'habitability-complaint' | 'deposit-demand' | 'rent-overcharge' | 'harassment-complaint';

export const DOCUMENT_TYPES: { id: DocumentType; label: string; icon: string; description: string }[] = [
  { id: 'eviction-answer', label: 'Answer to Eviction', icon: '⚖️', description: 'Formal legal answer with affirmative defenses' },
  { id: 'habitability-complaint', label: 'Habitability Complaint', icon: '🏚️', description: 'Notice of defect and repair demand' },
  { id: 'deposit-demand', label: 'Security Deposit Demand', icon: '💰', description: 'Demand for return of security deposit' },
  { id: 'rent-overcharge', label: 'Rent Overcharge Petition', icon: '📈', description: 'Challenge illegal rent increases' },
  { id: 'harassment-complaint', label: 'Harassment Complaint', icon: '🚨', description: 'Document landlord harassment pattern' },
];

interface DocVars {
  tenantName: string;
  landlordName: string;
  address: string;
  date: string;
  city: string;
  state: string;
  reason?: string;
  statutes: CityStatute[];
  postalCode?: string;
  depositAmount?: string;
  rentAmount?: string;
  increaseAmount?: string;
  issues?: string[];
}

export function compileDocument(type: DocumentType, vars: DocVars, cityData: CityData): string {
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  switch (type) {
    case 'eviction-answer':
      return `═══════════════════════════════════════════════════════════
NOTICE OF DEFECT AND ANSWER TO COMPLAINT FOR UNLAWFUL DETAINER
City of ${vars.city}, State of ${vars.state}
═══════════════════════════════════════════════════════════
Case No: _______________________
Filed: ${today}

DEFENDANT:  ${vars.tenantName}
PLAINTIFF:  ${vars.landlordName}
PROPERTY:   ${vars.address}
JURISDICTION: ${vars.city} Housing Court, ${vars.state}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

I. PRELIMINARY STATEMENT

The Defendant, ${vars.tenantName}, hereby appears and answers
the Complaint filed by ${vars.landlordName} and asserts the
following affirmative defenses pursuant to ${vars.state} state
law and ${vars.city} municipal housing codes.

The Defendant denies each and every allegation in the Complaint
except as specifically admitted herein.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

II. AFFIRMATIVE DEFENSES

${vars.statutes.slice(0, 3).map((s, i) => `
DEFENSE ${i + 1}: ${s.title}
Statute: ${s.code}
─────────────────────────────────────────────────────────
${s.description}

Application: ${i === 0
  ? `The Plaintiff has failed to maintain the premises in habitable condition as required by ${s.code}. Defendant documented defects on ${vars.date} and notified Plaintiff in writing. Plaintiff failed to remedy within the statutory period.`
  : i === 1
  ? `This eviction constitutes retaliation for Defendant's good-faith exercise of legal rights, including complaints to ${vars.city} code enforcement. The presumption of retaliation under ${s.code} applies.`
  : `The Defendant's rights under ${s.code} have been violated. The Plaintiff's actions fail to comply with the procedural requirements set forth in this statute.`
}`).join('\n')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

III. PRAYER FOR RELIEF

Defendant respectfully requests this Court:
(a) DISMISS the eviction complaint with prejudice;
(b) AWARD Defendant attorney fees and court costs;
(c) ORDER Plaintiff to make all necessary repairs;
(d) AWARD Defendant rent abatement for diminished habitability;
(e) GRANT any further relief the Court deems just and proper.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Date: ${today}

_________________________________
${vars.tenantName}, Defendant Pro Se

═══════════════════════════════════════════════════════════
Generated by CivicShield AI • ${vars.city}, ${vars.state}
Hybrid RAG Engine + Deterministic FSM Compiler
Zero Hallucination Legal Document Builder
═══════════════════════════════════════════════════════════`;

    case 'habitability-complaint':
      return `═══════════════════════════════════════════════════════════
NOTICE OF DEFECT AND DEMAND FOR REPAIR
═══════════════════════════════════════════════════════════

Date: ${today}

TO:     ${vars.landlordName}
FROM:   ${vars.tenantName}
RE:     Habitability Violations at ${vars.address}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Dear ${vars.landlordName},

Pursuant to ${vars.statutes[0]?.code || 'applicable housing code'}, I am
providing written notice of the following conditions at the above
premises that render the unit uninhabitable:

${(vars.issues || ['Defective heating system', 'Water leak / mold', 'Pest infestation']).map((issue, i) => `  ${i + 1}. ${issue}`).join('\n')}

These conditions violate ${vars.state} law and ${vars.city} municipal
housing code. You are hereby required to repair these conditions
within the statutory period.

LEGAL BASIS:
${vars.statutes.slice(0, 2).map(s => `• ${s.code} — ${s.title}`).join('\n')}

NOTICE: Failure to make repairs within the statutory period may
result in:
  - Rent withholding / abatement
  - Repair-and-deduct remedy
  - Complaint to ${vars.city} code enforcement
  - Affirmative defense in any eviction proceeding

This letter serves as written notice under ${vars.statutes[0]?.code}.
I expect a response within 5 business days.

Sincerely,
${vars.tenantName}
${vars.address}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by CivicShield AI • FSM Document Compiler`;

    case 'deposit-demand':
      return `═══════════════════════════════════════════════════════════
DEMAND FOR RETURN OF SECURITY DEPOSIT
═══════════════════════════════════════════════════════════

Date: ${today}

TO:     ${vars.landlordName}
FROM:   ${vars.tenantName}
RE:     Security Deposit — ${vars.address}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Dear ${vars.landlordName},

I am writing to demand the return of my security deposit for the
above-referenced premises.

Deposit Amount: ${vars.depositAmount || '$_________'}
Date Vacated:   ${vars.date}
Forwarding Address: [YOUR NEW ADDRESS]

LEGAL BASIS:
${vars.statutes.filter(s => s.keywords.some(k => k.includes('deposit'))).slice(0, 1).map(s =>
  `${s.code} — ${s.title}\n${s.description}`
).join('\n') || `Under ${vars.state} law, you are required to return the security
deposit within 14 days of my vacating the premises, along with an
itemized statement of any deductions.`}

NOTICE: Failure to return the deposit within the statutory period,
or failure to provide an itemized statement of deductions, results
in forfeiture of your right to retain any portion of the deposit.

${vars.state === 'New York' ? 'Under NY GOL § 7-108, you forfeit the entire deposit if no itemized statement is provided within 14 days.' : ''}
${vars.state === 'California' ? 'Under CA Civil Code § 1950.5, you must return the deposit within 21 days with an itemized statement.' : ''}

I expect full return of ${vars.depositAmount || 'my deposit'} within the
statutory deadline. Failure to comply will result in legal action
seeking the deposit amount plus statutory penalties.

Sincerely,
${vars.tenantName}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by CivicShield AI • FSM Document Compiler`;

    case 'rent-overcharge':
      return `═══════════════════════════════════════════════════════════
RENT OVERCHARGE COMPLAINT
═══════════════════════════════════════════════════════════

Date: ${today}

TO:     ${vars.city} Housing Authority / Rent Regulation Office
FROM:   ${vars.tenantName}
RE:     Illegal Rent Increase at ${vars.address}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

I, ${vars.tenantName}, residing at ${vars.address}, hereby file
this complaint regarding an illegal rent increase imposed by
${vars.landlordName}.

CURRENT RENT:  ${vars.rentAmount || '$_________'}
INCREASE:      ${vars.increaseAmount || '$_________'}
EFFECTIVE:     ${vars.date}

LEGAL VIOLATIONS:
${vars.statutes.filter(s => s.keywords.some(k =>
  k.includes('rent') || k.includes('increase') || k.includes('stabiliz')
)).slice(0, 2).map(s => `• ${s.code} — ${s.title}\n  ${s.description.substring(0, 150)}...`).join('\n\n')}

The above rent increase exceeds the maximum allowable increase
under applicable law. I request:
1. A rollback of rent to the legal maximum
2. Refund of any overpayment
3. Investigation of the landlord's rent history
4. Penalties as provided by law

${vars.tenantName}
${vars.address}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by CivicShield AI • FSM Document Compiler`;

    case 'harassment-complaint':
      return `═══════════════════════════════════════════════════════════
TENANT HARASSMENT COMPLAINT
═══════════════════════════════════════════════════════════

Date: ${today}

TO:     ${vars.city} Housing Authority
CC:     ${vars.landlordName}
FROM:   ${vars.tenantName}
RE:     Harassment at ${vars.address}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

I am filing this complaint against ${vars.landlordName} for
ongoing harassment at the above property.

INCIDENTS:
${(vars.issues || ['Threats of eviction', 'Refusal to make repairs', 'Disruption of services']).map((issue, i) =>
  `  ${i + 1}. ${issue} — Date: ___________`
).join('\n')}

LEGAL BASIS:
${vars.statutes.filter(s => s.keywords.some(k =>
  k.includes('harassment') || k.includes('retaliation') || k.includes('lockout')
)).slice(0, 2).map(s => `• ${s.code} — ${s.title}`).join('\n')}

These actions constitute landlord harassment under ${vars.city}
and ${vars.state} law. I request investigation and enforcement.

I have documented these incidents with [photos/written records/
witness statements] and am prepared to provide evidence.

${vars.tenantName}
${vars.address}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by CivicShield AI • FSM Document Compiler`;

    default:
      return 'Unknown document type';
  }
}
