import type { CityData } from '../cityData';
export const chicagoData: CityData = {
  id: 'chicago-il', name: 'Chicago', state: 'Illinois', mayor: 'Brandon Johnson', population: 2664452, councilName: 'Chicago City Council (50 Aldermen)',
  nodes: [
    { id: 'CC-Johnson', label: 'Mayor Brandon Johnson', group: 'council', value: 50, district: 'Mayor', description: 'Progressive mayor since 2023. Former CTU organizer. Affordable housing focus.', flagged: false },
    { id: 'CC-Ervin', label: 'Ald. Jason Ervin (28th Ward)', group: 'council', value: 40, district: '28th Ward', description: 'Finance Committee chair. West Side. Budget and development oversight.', flagged: true },
    { id: 'CC-Hopkins', label: 'Ald. Brian Hopkins (2nd Ward)', group: 'council', value: 38, district: '2nd Ward', description: 'Lincoln Park, Old Town, Gold Coast. Moderate. Development-friendly.', flagged: false },
    { id: 'CC-Rodriguez', label: 'Ald. Michael Rodriguez (22nd Ward)', group: 'council', value: 36, district: '22nd Ward', description: 'Little Village. Progressive. Anti-displacement. Tenant organizing background.', flagged: false },
    { id: 'CC-Hadden', label: 'Ald. Maria Hadden (49th Ward)', group: 'council', value: 35, district: '49th Ward', description: 'Rogers Park. Housing Committee. Tenant protections advocate.', flagged: false },
    { id: 'DEV-Sterling', label: 'Sterling Bay', group: 'developer', value: 48, description: 'Lincoln Yards $6B megadevelopment. TIF funding. 55 acres on North Side. Controversial rezoning.', flagged: true },
    { id: 'DEV-Related', label: 'Related Midwest', group: 'developer', value: 42, description: 'The 78 development. 62 acres South Loop. Major TIF recipient.', flagged: true },
    { id: 'DEV-JDL', label: 'JDL Development', group: 'developer', value: 35, description: 'Major Chicago developer. Multiple luxury projects. Political donor.', flagged: false },
    { id: 'ZON-TIF', label: 'TIF Districts', group: 'zoning', value: 38, description: 'Tax Increment Financing. 130+ TIF districts. $1.4B diverted from schools/services. Developer subsidy mechanism.', flagged: true },
    { id: 'ZON-RLTO', label: 'RLTO (Tenant Ordinance)', group: 'zoning', value: 30, description: 'Chicago Residential Landlord Tenant Ordinance. Strong tenant protections. Security deposit rules. Retaliation ban.', flagged: false },
    { id: 'TEN-MTO', label: 'Metropolitan Tenants Org', group: 'tenant', value: 28, description: 'Oldest tenant organization in Chicago. Hotline. Legal clinics. Anti-eviction defense.', flagged: false },
    { id: 'TEN-LAF', label: 'Legal Aid Chicago', group: 'tenant', value: 25, description: 'Free legal representation for low-income tenants in eviction court.', flagged: false },
    { id: 'LOB-CAR', label: 'Chicago Assoc of Realtors', group: 'lobby', value: 30, description: 'Real estate industry lobby. Opposes rent control. Political spending on aldermanic races.', flagged: true },
  ],
  links: [
    { source: 'DEV-Sterling', target: 'ZON-TIF', value: 30, label: 'Lincoln Yards TIF $1.3B', type: 'exemption' },
    { source: 'DEV-Related', target: 'ZON-TIF', value: 25, label: 'The 78 TIF recipient', type: 'exemption' },
    { source: 'CC-Ervin', target: 'ZON-TIF', value: 18, label: 'Finance Committee TIF oversight', type: 'vote' },
    { source: 'CC-Hopkins', target: 'DEV-Sterling', value: 15, label: 'Lincoln Yards district approval', type: 'vote' },
    { source: 'LOB-CAR', target: 'CC-Hopkins', value: 12, label: 'Campaign contributions', type: 'funding' },
    { source: 'TEN-MTO', target: 'CC-Rodriguez', value: 10, label: 'Tenant organizing support', type: 'lobbying' },
    { source: 'TEN-MTO', target: 'ZON-RLTO', value: 8, label: 'RLTO enforcement advocacy', type: 'lobbying' },
    { source: 'LOB-CAR', target: 'CC-Ervin', value: 10, label: 'Campaign contributions', type: 'funding' },
    { source: 'CC-Hadden', target: 'ZON-RLTO', value: 12, label: 'Tenant protection expansion', type: 'vote' },
    { source: 'DEV-JDL', target: 'ZON-TIF', value: 14, label: 'TIF-funded projects', type: 'exemption' },
  ],
  anomalies: [
    { id: 1, type: 'TIF Diversion', description: 'Lincoln Yards: $1.3B in TIF funds diverted from schools and services to Sterling Bay mega-development on North Side. 50 aldermen approved despite community opposition.', severity: 'critical', relatedNodes: ['DEV-Sterling', 'ZON-TIF', 'CC-Hopkins'], centrality: 0.88 },
    { id: 2, type: 'Aldermanic Privilege', description: 'Chicago aldermanic prerogative gives single alderman veto power over zoning in their ward. Creates pay-to-play dynamic with developers seeking zoning changes.', severity: 'high', relatedNodes: ['CC-Ervin', 'ZON-TIF'], centrality: 0.82 },
    { id: 3, type: 'Serial Eviction Filing', description: 'Corporate landlords filing mass evictions in South and West Side zip codes (60621, 60624, 60636). 40% dismissed but tenants displaced by process.', severity: 'high', relatedNodes: ['TEN-MTO', 'TEN-LAF'], centrality: 0.75 },
  ],
  statutes: [
    { id: 1, code: 'Chicago RLTO § 5-12', title: 'Residential Landlord Tenant Ordinance', description: 'Chicago-specific tenant protections. Requires written lease. Security deposit in interest-bearing account. Return within 30 days. Penalties for violations: 2x deposit.', keywords: ['RLTO', 'deposit', 'lease', 'Chicago'], relevanceScore: 95, source: 'Chicago Municipal Code' },
    { id: 2, code: '735 ILCS 5/9-207.5', title: 'Illinois Eviction Notice Requirements', description: '5-day notice for nonpayment. 10-day notice for lease violation. 30-day notice for month-to-month. Tenant can cure within notice period.', keywords: ['eviction', 'notice', '5 day', '10 day'], relevanceScore: 93, source: 'Illinois Compiled Statutes' },
    { id: 3, code: 'Chicago RLTO § 5-12-150', title: 'Retaliation Ban', description: 'Landlord may not retaliate for tenant complaints, organizing, or exercising legal rights. Presumption of retaliation within 12 months of protected activity.', keywords: ['retaliation', 'complaint', 'organizing'], relevanceScore: 90, source: 'Chicago Municipal Code' },
    { id: 4, code: 'Chicago RLTO § 5-12-160', title: 'Lockout and Utility Shutoff Ban', description: 'Illegal to change locks, shut off utilities, or remove tenant property without court order. Tenant entitled to 2 months rent in damages plus attorney fees.', keywords: ['lockout', 'utilities', 'self-help', 'damages'], relevanceScore: 92, source: 'Chicago Municipal Code' },
    { id: 5, code: '765 ILCS 735', title: 'Illinois Security Deposit Return Act', description: 'Landlord must return deposit within 30 days for units 5+. Itemized statement required. Failure to comply: 2x deposit amount in penalties.', keywords: ['deposit', 'return', '30 days', 'penalty'], relevanceScore: 85, source: 'Illinois Compiled Statutes' },
  ],
  hotspots: [
    { zipCode: '60621', neighborhood: 'Englewood', evictionRate: 32.1, recentCases: 380, trend: 'rising', lat: 41.779, lng: -87.644 },
    { zipCode: '60624', neighborhood: 'West Garfield Park', evictionRate: 28.4, recentCases: 290, trend: 'rising', lat: 41.881, lng: -87.728 },
    { zipCode: '60636', neighborhood: 'West Englewood', evictionRate: 26.8, recentCases: 260, trend: 'rising', lat: 41.772, lng: -87.668 },
    { zipCode: '60644', neighborhood: 'Austin', evictionRate: 24.3, recentCases: 340, trend: 'stable', lat: 41.886, lng: -87.766 },
    { zipCode: '60649', neighborhood: 'South Shore', evictionRate: 22.7, recentCases: 215, trend: 'rising', lat: 41.762, lng: -87.565 },
    { zipCode: '60609', neighborhood: 'Back of the Yards', evictionRate: 18.5, recentCases: 175, trend: 'stable', lat: 41.820, lng: -87.656 },
    { zipCode: '60647', neighborhood: 'Logan Square', evictionRate: 12.4, recentCases: 120, trend: 'stable', lat: 41.928, lng: -87.699 },
    { zipCode: '60614', neighborhood: 'Lincoln Park', evictionRate: 6.8, recentCases: 55, trend: 'declining', lat: 41.924, lng: -87.651 },
  ],
  stats: { totalEvictionsLogged: 18450, activeHotspots: 5, anomaliesDetected: 3, tenantsProtected: 42300, zoningExemptions: 130 },
};
