'use client';
import React, { useState, useEffect } from 'react';
import { AlertTriangle, Shield, X } from 'lucide-react';

export default function LegalDisclaimer() {
  const [show, setShow] = useState(false);

  useEffect(() => {
    const dismissed = sessionStorage.getItem('civicshield-disclaimer');
    if (!dismissed) setShow(true);
  }, []);

  const dismiss = () => {
    sessionStorage.setItem('civicshield-disclaimer', '1');
    setShow(false);
  };

  if (!show) return null;

  return (
    <div className="fixed inset-0 bg-black/80 backdrop-blur-sm flex items-center justify-center z-[200] p-4">
      <div className="max-w-lg w-full bg-zinc-900 border border-zinc-700 rounded-3xl p-8 shadow-2xl">
        <div className="flex items-center gap-3 mb-6">
          <div className="w-12 h-12 bg-amber-500/10 rounded-2xl flex items-center justify-center">
            <Shield className="w-7 h-7 text-amber-400" />
          </div>
          <div>
            <h2 className="text-xl font-semibold text-white">Legal Disclaimer</h2>
            <p className="text-xs text-zinc-400">Please read before using CivicShield AI</p>
          </div>
        </div>

        <div className="space-y-4 text-sm text-zinc-200 leading-relaxed">
          <p>
            <strong className="text-white">CivicShield AI provides legal information, NOT legal advice.</strong> The documents, risk scores, and chat responses generated by this platform are for educational and informational purposes only.
          </p>
          <p>
            This tool does <strong className="text-white">not</strong> create an attorney-client relationship. No attorney has reviewed your specific case through this platform.
          </p>
          <p>
            <strong className="text-white">For your specific legal situation</strong>, you should consult with a licensed attorney in your jurisdiction. Many cities offer free legal representation through Right to Counsel programs — check the Lawyer Directory for options.
          </p>
          <p className="text-xs text-zinc-400">
            Institutional anomaly data is based on public records analysis and structural graph algorithms. It does not constitute evidence of wrongdoing.
          </p>
        </div>

        <div className="mt-8 flex items-center gap-3">
          <button
            onClick={dismiss}
            className="flex-1 py-3 bg-white text-black rounded-xl font-semibold hover:bg-emerald-300 transition-colors text-sm"
          >
            I Understand — Continue
          </button>
        </div>

        <div className="mt-4 text-[10px] text-zinc-600 text-center">
          This disclaimer will not be shown again during this session.
        </div>
      </div>
    </div>
  );
}
